grafana:
  adminUser: admin
  adminPassword: admin
  persistence:
    enabled: true
    size: 5Gi
  service:
    type: ClusterIP

prometheus:
  prometheusSpec:
    retention: 7d
    serviceMonitorSelector: {}
    podMonitorSelector: {}
