apiVersion: v1
kind: Pod
metadata:
  name: load-generator
  namespace: web-app
spec:
  restartPolicy: Never
  containers:
  - name: load-generator
    image: busybox:1.35
    command: ["/bin/sh", "-c"]
    args:
      - |
        i=1
        while true; do
          wget -q -O- http://flask-app-service.web-app.svc.cluster.local/ > /dev/null
          echo "Request $i sent at $(date)"
          i=$((i+1))
          sleep 0.1
        done
