apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: web-app
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk  # rootpassword
  MYSQL_USER: YXBwdXNlcg==               # appuser
  MYSQL_PASSWORD: YXBwcGFzc3dvcmQ=       # apppassword
     
